name: consonum
services:
 
  # DB
  mariadb:
    env_file: .env.staging
    image: mariadb:11.2
    container_name: consonum_mariadb_staging
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - consonum_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  # BACKEND SYMFONY

  backend:
    env_file: .env.staging
    build:
      context: ./backend
      dockerfile: Dockerfile.staging
    container_name: consonum_backend_staging
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./backend/config/jwt:/app/config/jwt:ro
      - ./backend/var:/app/var
      - ./.env.staging:/app/.env:ro
    networks:
      - consonum_network
    expose:
      - "9000"

  # NGINX (Reverse Proxy Backend)
  nginx:
    image: nginx:alpine
    container_name: consonum_nginx_staging
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/public:/app/public:ro
      - ./nginx/staging.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - consonum_network

  # FRONTEND NEXT.JS
  frontend:
    env_file: .env.staging
    build:
      context: ./frontend
      dockerfile: Dockerfile.staging
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
    container_name: consonum_frontend_staging
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NODE_ENV: staging
    expose:
      - "3000"
    networks:
      - consonum_network
# VOLUMES
volumes:
  mariadb_data:
    driver: local

# NETWORK
networks:
  consonum_network:
    driver: bridge
