security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email 

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        #login path firewall
        login:
            pattern: ^/api/auth/login
            stateless: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /api/auth/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        #webhook
        webhook:
            pattern: ^/api/payment/webhook
            stateless: true
            security: false

        # API firweel - all begins by /api.
        api:
            pattern:   ^/api
            stateless: true
            jwt: ~ 

    # Access Rules
    access_control:
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/verify, roles: PUBLIC_ACCESS }
        - { path: ^/api/data-request, roles: PUBLIC_ACCESS }
        - { path: ^/api/payment/webhook, roles: PUBLIC_ACCESS }

        # path begins by /api need to be identified.
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
