<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxMTwN4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxMTwN4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYxMTwN4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYxMTwN4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYxMTwN4\App_KernelDevDebugContainer([
    'container.build_hash' => 'YxMTwN4',
    'container.build_id' => 'c539d635',
    'container.build_time' => 1762784475,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxMTwN4');
