upstream frontend {
    server frontend:3000;
}

# Redirection HTTP → HTTPS
server {
    listen 80;
    server_name consonum.fr www.consonum.fr;
    return 301 https://consonum.fr$request_uri;
}

# Serveur HTTPS
server {
    listen 443 ssl;
    server_name consonum.fr www.consonum.fr;
    
    # Certificats SSL
    ssl_certificate /etc/letsencrypt/live/consonum.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/consonum.fr/privkey.pem;

    #CSP
        add_header Content-Security-Policy "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://js.stripe.com; frame-src https://js.stripe.com https://hooks.stripe.com; connect-src 'self' https://api.stripe.com;" always;

    
    # Backend Symfony API (FastCGI)
    location /api {
        root /app/public;
        try_files $uri /index.php$request_uri;
        fastcgi_pass backend:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app/public/index.php;
        fastcgi_param DOCUMENT_ROOT /app/public;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
    
    # Frontend Next.js (Proxy HTTP)
    location / {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}