name: Deploy to Production

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
    - name: Deploy to Staging
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/EcoNum
          git pull origin DEVELOP
          docker-compose --env-file .env.staging -f docker-compose.staging.yml down
          docker-compose --env-file .env.staging -f docker-compose.staging.yml up -d --build
  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to Production
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        proxy_host: ${{ secrets.BASTION_IP }}
        proxy_username: root
        proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/EcoNum
          git pull origin main
          docker compose -f docker-compose.prod.yml down
          docker compose -f docker-compose.prod.yml build
          docker compose -f docker-compose.prod.yml up -d